### PR TITLE
Update kokkos-kernels exercises build for post 3.0

### PR DESCRIPTION
**Pull request by ndellingwood**
Add script run_installlibs_cmake.sh to install kokkos, kokkos-kernels,
    then call cmake to generate Makefile for each exercise

### CODE REVIEW

**Comment by ndellingwood** [comment]
@jjwilke @srajama1 @brian-kelley @seheracer @lucbv @vqd8a @ e10harvey @kyungjoo-kim
These changes add a script (and remove the broken Makefiles) to handle the kokkos-kernels exercises for version >= 3.0 - the scripts will install kokkos and kokkos-kernels, and call cmake to generate the makefile.
Let me know if you have feedback, requests for changes, etc. before merge.

**Comment by lucbv** [comment]
Yeah that looks good to me. The only comment I have is that you are turning off the examples in kokkos-kernels' configuration which means that "example/wiki/sparse" examples won't compile even though we reference them in the tutorial slides.

**Comment by ndellingwood** [comment]
> Yeah that looks good to me. The only comment I have is that you are turning off the examples in kokkos-kernels' configuration which means that "example/wiki/sparse" examples won't compile even though we reference them in the tutorial slides.

@lucbv I ran into a build error with tests disabled and examples enabled (something to do with gtest), I'll follow up with you to figure out what I should do different and we can reenable the examples once we get it resolved.

**Comment by ndellingwood** [comment]
Thanks all, merging this in for now to have a scripting option in place to compile the existing exercises. We can rename the scripts, enhance, split out capabilities etc as desired.

**Pull request merged**
